### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Ozlemturkmen** [AzizKpln/Beef-Over-AWS#1]

**Comment by AzizKpln** [comment]
What is the issue? I've tested it 5 times on different machines and havent encountred with any problem

**Comment by AzizKpln** [comment]
Be sure that you are using the latest version of your operating system by the way

**Comment by Ozlemturkmen** [comment]
[-]Please run this script without root privilages.. whoami changed root edit.
Hatası vardı. whoiam yazanları root yaparak açtım install ve diğer dosya sorunsuz calışıyor gibiydi. Beef ve ngrok için ayarlamaları da yaptırdım. Sonrasında sorunsuz videodaki gibi linkleri verdi ama açılmıyordu hiç birisi...

**Comment by AzizKpln** [comment]
O zaman beef düzgün kurulmamıştır. Eğer güncel sürüm kullanmıyorsan olabilecek bir şey. Hangi işletim sistemini kullanıyorsan sitesine gidip son sürüm İSO dosyasını indir ve kur düzelecektir

**Comment by Ozlemturkmen** [comment]
Beefte ngrok da harici olarak denediğimde açılıyor. En güncel sürüm diğer apt-kurulumlarını yaptım. Hatta üşenmedim kodlamayı açıp öncesinde kendi kullandığım beef ve ngrok yollarını gösterip de denedim yine olmuyor. Talebimi kapatmayın lütfen. Sürüm son sürüm çünkü

**Comment by AzizKpln** [comment]
install.sh dosyasını çalıştırdınız mı?

**Comment by Ozlemturkmen** [comment]
Zaten ilk git cloneden sonra ilk bunu calıştırdım. En baştaki hatayı aldım youtubedeki videoda biri sormuş rootsuz hesapla girin demişsiniz onu yapamadım. O yüzden install.sh ve diğer açtığımız dosyalardaki who ile başlayan kısımları root yaparak kurulumları gerçekleştirdim. Ngrok için ekstra yeni üyelikte açtım auth kodunu girdim bağlayabiliyor ama nedense linkleri açmıyor. Beef ve ngrok'u harici calıştırdım bu arada denemek için calışmakta

**Comment by AzizKpln** [comment]
maalesef yazdığınızı anlayamıyorum fakat şuanda temiz bir debian makine kurdum. Test edeceğim birazdan.

**Comment by AzizKpln** [comment]
test ettim. Problemsiz çalışıyor hiçbir şekilde güncelliğini yitirmedi. Bir şeyleri hatalı yapıyorsunuz sanırsam

**Comment by Ozlemturkmen** [comment]
Birde şeyi farkettim internette sizin bu yazdığınız gibi bir sistem daha var.  ./ngrok start --all yapıyorlar tunnel açabiliyor free olanlarda bende hiç olmadı bu. yml dosyasını da editledim yeniden de kurdum. Belki de bundan dolayı calışmıyor
