### ISSUE TITLE
Won't work on my target.

### ISSUE THREAD

**Issue by cloutvisuals** [AzizKpln/Beef-Over-AWS#4]
Hello I have followed the video i'm able to log in on beef without a problem I get the logs whenever I use the link on myself but when I send it to my friends it doesn't send me a log and the page won't load for my friend.

**Comment by AzizKpln** [comment]
Hi
i believe you have sent your local ip address to your friend. Please open the http port on your modem interface if you're using this script on your local pc. Then issue this command:

>  systemctl start apache2.service

and send your public ip address to your friend. You'll be able to issue js codes to your friend now. 

In fact, this script is coded for servers. You won't be encountring with these kind of issues when you use this tool on a server. Still, this tool works both on a server and a local pc but you have to give a little bit effort for this script to run on your local pc.

**Comment by cloutvisuals** [comment]
I have sent him the inet ip from kali linux, and also forwarded the port ''3000'' on my router.

**Comment by cloutvisuals** [comment]
But still doesn't work for some reason.

**Comment by cloutvisuals** [comment]
![image](https://user-images.githubusercontent.com/81836414/113577790-b6ca6b80-9619-11eb-93b8-1aa5ed5cde99.png)

**Comment by VortexVoltGIT** [comment]
Not the Inet IP Send your public IP address

**Comment by VortexVoltGIT** [comment]
Search Up what is my ip
