### ISSUE TITLE
BeEf still won't work on my target.

### ISSUE THREAD

**Issue by cloutvisuals** [AzizKpln/Beef-Over-AWS#5]
I have done what you said, but still doesn't work I port forwarded the port ''3000'' and used the mac address and inet ip address from Kali Linux to port forward it via my router, And kali linux is on a bridged adapter I have done everything you said and followed through the video.  I can hook myself without a problem but not others.

**Comment by AzizKpln** [comment]
No you have not acutally. Inet is your local ip address. I told you to use your public ip address :)
