### ISSUE TITLE
Beef is not working either for me or others

### ISSUE THREAD

**Issue by iLaurian** [AzizKpln/Beef-Over-AWS#9]
I have followed the video till the end, but when I go to my public ip
I get the Hacked message, but nothing shows up in the BEEF panel.

**Comment by iLaurian** [comment]
I did not port forward port 80.

**Comment by AzizKpln** [comment]
Im testing it

**Comment by iLaurian** [comment]
Do you want any logs or screenshots or anything?

**Comment by AzizKpln** [comment]
no. I tested it now. The tool works as the way it should. You're doing something wrong
![324](https://user-images.githubusercontent.com/28807419/149660483-77e7acaf-51ad-4d86-8907-80e088cb20ef.PNG)
.

**Comment by aurhack** [comment]
hello, after setting up all, it provides a webpage with hook ro not? i can't see the yt video so it's hard to setup correct
